CREATE TABLE "search_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "search_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid,
	"risk_assessment_id" bigint,
	"postno" text NOT NULL,
	"address" text NOT NULL,
	"detail_address" text NOT NULL,
	"reg_dt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "update_password_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "update_password_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid,
	"password" text NOT NULL,
	"reg_dt" timestamp DEFAULT now() NOT NULL
);

--> statement-breakpoint
CREATE TABLE "risk_assessment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "risk_assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"result_json" jsonb,
	"risk_assessment_model_id" bigint,
	"reg_dt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "risk_assessment_model" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "risk_assessment_model_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"model_name" text NOT NULL,
	"reg_dt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "search_history" ADD CONSTRAINT "search_history_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_history" ADD CONSTRAINT "search_history_risk_assessment_id_risk_assessment_id_fk" FOREIGN KEY ("risk_assessment_id") REFERENCES "public"."risk_assessment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "update_password_history" ADD CONSTRAINT "update_password_history_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "risk_assessment" ADD CONSTRAINT "risk_assessment_risk_assessment_model_id_risk_assessment_model_id_fk" FOREIGN KEY ("risk_assessment_model_id") REFERENCES "public"."risk_assessment_model"("id") ON DELETE cascade ON UPDATE no action;